version: "3.7"

services:
#     nginx-proxy:
#         image: jwilder/nginx-proxy:alpine
#         ports:
#             - 9008:80
#         volumes:
#             - /var/run/docker.sock:/tmp/docker.sock:ro
    web:
        image: nginx:alpine
        ports:
          - "8000:80"
          - "443:443"
        volumes:
            - ./default:/etc/nginx/conf.d/default.conf
    app:
        build: ./docker
        volumes:
            - .:/var/www
        working_dir: /var/www
        links:
            - db
        depends_on:
            - db

        tty: true

    db:
        image: postgres
        restart: on-failure
        ports:
            - "5433:5432"
        volumes:
            # - /var/run/postgresql:/var/run/postgresql
            # - /var/pgsql_socket:/var/pgsql_socket
            - ./database.sh:/docker-entrypoint-initdb.d/database.sh
        environment:
            - POSTGRES_USER=root
                
        # command: >
        #     bash -c "ln -s /private/tmp/.s.PGSQL.5432 /var/pgsql_socket/ &&
        #         su postgres &&
        #         psql &&
        #         CREATE DATABASE wiser_med"
    composer:
        image: composer:1.9.0
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: install
        depends_on:
            - app
